// <auto-generated />
using System;
using IndoorLocalization.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IndoorLocalization.Migrations
{
    [DbContext(typeof(IndoorLocalizationContext))]
    [Migration("20251209094659_CreateOtpCodesTable")]
    partial class CreateOtpCodesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IndoorLocalization.Models.Entities.Asset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<long?>("FloorMapId")
                        .HasColumnType("bigint")
                        .HasColumnName("floormapid");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastsync");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<double?>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double?>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("assets_pkey");

                    b.HasIndex("FloorMapId");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.AssetPositionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("assetid");

                    b.Property<DateTime?>("DateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("FloorMapId")
                        .HasColumnType("bigint")
                        .HasColumnName("floormapid");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("assetpositionhistory_pkey");

                    b.HasIndex("AssetId");

                    b.HasIndex("FloorMapId");

                    b.ToTable("assetpositionhistory", (string)null);
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.AssetZoneHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("assetid");

                    b.Property<DateTime>("EnterDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enterdatetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExitDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exitdatetime");

                    b.Property<TimeSpan?>("RetentionTime")
                        .HasColumnType("interval")
                        .HasColumnName("retentiontime");

                    b.Property<long?>("ZoneId")
                        .HasColumnType("bigint")
                        .HasColumnName("zoneid");

                    b.HasKey("Id")
                        .HasName("assetzonehistory_pkey");

                    b.HasIndex("AssetId");

                    b.HasIndex("ZoneId");

                    b.ToTable("assetzonehistory", (string)null);
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.FloorMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("HeightInMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("height_m");

                    b.Property<int?>("ImageHeightPx")
                        .HasColumnType("integer")
                        .HasColumnName("image_height_px");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int?>("ImageWidthPx")
                        .HasColumnType("integer")
                        .HasColumnName("image_width_px");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<double>("WidthInMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("width_m");

                    b.HasKey("Id")
                        .HasName("floormaps_pkey");

                    b.ToTable("floormaps", (string)null);
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.OtpCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lastname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refreshtoken");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refreshtokenexpiry");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.Zone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Points")
                        .HasColumnType("jsonb")
                        .HasColumnName("points");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("zones_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.Asset", b =>
                {
                    b.HasOne("IndoorLocalization.Models.Entities.FloorMap", "FloorMap")
                        .WithMany("Assets")
                        .HasForeignKey("FloorMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("assets_floormapid_fkey");

                    b.Navigation("FloorMap");
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.AssetPositionHistory", b =>
                {
                    b.HasOne("IndoorLocalization.Models.Entities.Asset", "Asset")
                        .WithMany("AssetPositionHistories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("assetpositionhistory_assetid_fkey");

                    b.HasOne("IndoorLocalization.Models.Entities.FloorMap", "FloorMap")
                        .WithMany("AssetPositionHistories")
                        .HasForeignKey("FloorMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("assetpositionhistory_floormapid_fkey");

                    b.Navigation("Asset");

                    b.Navigation("FloorMap");
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.AssetZoneHistory", b =>
                {
                    b.HasOne("IndoorLocalization.Models.Entities.Asset", "Asset")
                        .WithMany("AssetZoneHistories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("assetzonehistory_assetid_fkey");

                    b.HasOne("IndoorLocalization.Models.Entities.Zone", "Zone")
                        .WithMany("AssetZoneHistories")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("assetzonehistory_zoneid_fkey");

                    b.Navigation("Asset");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.OtpCode", b =>
                {
                    b.HasOne("IndoorLocalization.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.Zone", b =>
                {
                    b.HasOne("IndoorLocalization.Models.Entities.User", "User")
                        .WithMany("Zones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("zones_userid_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.Asset", b =>
                {
                    b.Navigation("AssetPositionHistories");

                    b.Navigation("AssetZoneHistories");
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.FloorMap", b =>
                {
                    b.Navigation("AssetPositionHistories");

                    b.Navigation("Assets");
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.User", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("IndoorLocalization.Models.Entities.Zone", b =>
                {
                    b.Navigation("AssetZoneHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
